[GENERAL]
twitter_name = ""
update_interval = "1H"

[BULLISH]
twitter_name_bullish_suffix = "[PUMPIT]"
twitter_bullish_description = "To the moon!!!!!"
twitter_bullish_profile_color = "#00AA00"

[BEARISH]
twitter_name_bearish_suffix = "[DUMPIT]"
twitter_bearish_description = "Should have sold. :("
twitter_bearish_profile_color = "#FF001F"
